# Generated by Django 3.2.20 on 2023-08-12 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.IntegerField()),
                ('title', models.CharField(max_length=50)),
                ('image', models.CharField(max_length=200)),
                ('summary', models.TextField()),
                ('write_time', models.CharField(max_length=20)),
                ('url', models.CharField(max_length=50)),
            ],
        ),
    ]
