# Generated by Django 3.2.20 on 2023-08-12 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('_id', models.IntegerField(primary_key=True, serialize=False)),
                ('category', models.IntegerField()),
                ('title', models.CharField(max_length=50)),
                ('image', models.FilePathField(null=True)),
                ('summary', models.TextField()),
                ('write_time', models.CharField(max_length=20)),
                ('url', models.FilePathField()),
            ],
            options={
                'db_table': 'news',
            },
        ),
    ]
