# Generated by Django 3.2.20 on 2023-08-12 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_news_newsid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='id',
        ),
        migrations.AlterField(
            model_name='news',
            name='newsid',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
