# Generated by Django 3.2.20 on 2023-08-14 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_rename_write_time_news_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-time']},
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='news',
            name='url',
            field=models.CharField(max_length=100),
        ),
    ]
